services:
  postgres:
    container_name: easy-buy-postgresql
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - easy-buy-network
    restart: unless-stopped
  mongodb:
    container_name: easy-buy-mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  mail-dev:
    container_name: easy-buy-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  easy-buy-network:
    driver: bridge
volumes:
  postgresql:
  pgadmin:
  mongo: